owner: JonathanTreffler
repo: status

sites:
  - name: jonathan-treffler.de
    url: https://jonathan-treffler.de
  - name: domspatzen-quantum.de
    url: https://domspatzen-quantum.de

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Jonathan Treffler Server Status
  introTitle: Server Uptime run by Github Actions
  introMessage: 
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER
